#!/bin/bash

set -e

SRC_FILE="$1"
DST_PATH="$2"

VERSION=1.0.0

info() {
     local green="\033[1;32m"
     local normal="\033[0m"
     echo -e "[${green}INFO${normal}] $1"
}

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo -e "[${red}ERROR${normal}] $1"
}

usage() {
cat << EOF
VERSION: $VERSION
USAGE:
    $0 source_file.png destination_path

DESCRIPTION:
    This script makes all the AppIcon for XCode 8.1.

    source_file.png  - The source png image.
    destination_path - The destination path where the finished icons go.

    This script uses ImageMagick. 
    Use 'brew install ImageMagick' to install it.


EXAMPLE:
    ios-icon-generator 1024.png ~/123
EOF
}

# Check ImageMagick
command -v convert >/dev/null 2>&1 || { error >&2 "The ImageMagick is not installed. Please use brew to install it first."; exit -1; }

# Check param
if [ $# != 2 ];then
    usage
    exit -1
fi

# Check dst path whether exist.
if [ ! -d "$DST_PATH" ];then
    mkdir -p "$DST_PATH"
fi

# iOS icon specs: https://developer.apple.com/library/ios/qa/qa1686/_index.html

info 'Generate iTunesArtwork.png ...'
convert "$SRC_FILE" -resize 512x512 "$DST_PATH/iTunesArtwork.png"
info 'Generate iTunesArtwork@2x.png ...'
convert "$SRC_FILE" -resize 1024x1024 "$DST_PATH/iTunesArtwork@2x.png"

info 'Generate icon_20pt.png ...'
convert "$SRC_FILE" -resize 20x20 "$DST_PATH/icon_20pt.png"
info 'Generate icon_20pt@2x.png ...'
convert "$SRC_FILE" -resize 40x40 "$DST_PATH/icon_20pt@2x.png"
info 'Generate icon_20pt@3x.png ...'
convert "$SRC_FILE" -resize 60x60 "$DST_PATH/icon_20pt@3x.png"

info 'Generate icon_29pt.png ...'
convert "$SRC_FILE" -resize 29x29 "$DST_PATH/icon_29pt.png"
info 'Generate icon_29pt@2x.png ...'
convert "$SRC_FILE" -resize 58x58 "$DST_PATH/icon_29pt@2x.png"
info 'Generate icon_29pt@3x.png ...'
convert "$SRC_FILE" -resize 87x87 "$DST_PATH/icon_29pt@3x.png"

info 'Generate icon_40pt.png ...'
convert "$SRC_FILE" -resize 40x40 "$DST_PATH/icon_40pt.png"
info 'Generate icon_40pt@2x.png ...'
convert "$SRC_FILE" -resize 80x80 "$DST_PATH/icon_40pt@2x.png"
info 'Generate icon_40pt@3x.png ...'
convert "$SRC_FILE" -resize 120x120 "$DST_PATH/icon_40pt@3x.png"

info 'Generate icon_57pt.png ...'
convert "$SRC_FILE" -resize 57x57 "$DST_PATH/icon_57pt.png"
info 'Generate icon_57pt@2x.png ...'
convert "$SRC_FILE" -resize 114x114 "$DST_PATH/icon_57pt@2x.png"
info 'Generate icon_57pt@3x.png ...'
convert "$SRC_FILE" -resize 171x171 "$DST_PATH/icon_57pt@3x.png"

info 'Generate icon_60pt.png ...'
convert "$SRC_FILE" -resize 60x60 "$DST_PATH/icon_60pt.png"
info 'Generate icon_60pt@2x.png ...'
convert "$SRC_FILE" -resize 120x120 "$DST_PATH/icon_60pt@2x.png"
info 'Generate icon_60pt@3x.png ...'
convert "$SRC_FILE" -resize 180x180 "$DST_PATH/icon_60pt@3x.png"

info 'Generate icon_76pt.png ...'
convert "$SRC_FILE" -resize 76x76 "$DST_PATH/icon_76pt.png"
info 'Generate icon_76pt@2x.png ...'
convert "$SRC_FILE" -resize 152x152 "$DST_PATH/icon_76pt@2x.png"
info 'Generate icon_76pt@3x.png ...'
convert "$SRC_FILE" -resize 228x228 "$DST_PATH/icon_76pt@3x.png"

info 'Generate icon_83.5pt@2x.png ...'
convert "$SRC_FILE" -resize 167x167 "$DST_PATH/icon_83.5pt@2x.png"

info 'Generate icon_24pt@2x.png ...'
convert "$SRC_FILE" -resize 48x48 "$DST_PATH/icon_24pt@2x.png"
info 'Generate icon_27.5pt@2x.png ...'
convert "$SRC_FILE" -resize 55x55 "$DST_PATH/icon_27.5pt@2x.png"

info 'Generate icon_86pt@2x.png ...'
convert "$SRC_FILE" -resize 172x172 "$DST_PATH/icon_86pt@2x.png"
info 'Generate icon_98pt@2x.png ...'
convert "$SRC_FILE" -resize 196x196 "$DST_PATH/icon_98pt@2x.png"

info 'Generate Done.'
